module.exports = {
  projects: [
    '<rootDir>/apps/playground',
    '<rootDir>/libs/playground/shared/data-access/idb',
    '<rootDir>/libs/playground/shared/idb/data-access',
    '<rootDir>/libs/playground/shared/idb/util',
    '<rootDir>/libs/playgrond/shared/ui/data-access',
    '<rootDir>/libs/playground/shared/ui/data-access',
    '<rootDir>/libs/playground/shared/ui/util',
    '<rootDir>/libs/playground/shared/ui/components/footer',
    '<rootDir>/libs/playground/shared/ui/components/header',
    '<rootDir>/libs/playground/shared/ui/components/icon',
    '<rootDir>/libs/playground/shared/ui/components/loading',
    '<rootDir>/libs/playground/shared/ui/components/page',
    '<rootDir>/libs/playground/shell',
    '<rootDir>/libs/playground/todos/feature',
    '<rootDir>/libs/playground/todos/data-access',
    '<rootDir>/libs/playground/shared/utils/rx',
    '<rootDir>/libs/playground/shared/utils/types',
    '<rootDir>/libs/playground/shared/ui/components/forms',
    '<rootDir>/libs/playground/home/feature',
  ],
}
