name: Run deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Run deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Run deployment
        run: |
          yarn
          yarn run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
