name: Run deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Run deployment
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node-version: [ 12.x ]
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run deployment
        run: |
          yarn
          yarn run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
